title: Rahul Chintalapati
position: Masters In Computer Engineering
affiliation: Bradley Department of Electrical and Computer Engineering, Virginia Tech
affiliation_link: https://ece.vt.edu/
email: crahulvarma@vt.edu
keywords: 
google_scholar: 
cv_link: https://my-pdf-files.yyliu.net/Yaoyao_Liu_Resume.pdf
github_link: https://github.com/RahulVarmaC
linkedin: https://www.linkedin.com/in/rahulvarmac/
twitter:
avatar: https://images.yyliu.net/avatar.jpg
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: Yaoyao Liu is a Ph.D. candidate at Max Planck Institute for Informatics. His research lies in meta-learning, incremental learning, and image generation.
canonical: 
imprint: 
data_protection: 
