title: Rahul Chintalapati
position: Masters In Computer Engineering
affiliation: Bradley Department of Electrical and Computer Engineering, Virginia Tech
affiliation_link: https://ece.vt.edu/
email: crahulvarma@vt.edu
keywords: 
cv_link: https://drive.google.com/file/d/1FGtzEQo4nCEvnmSZd588C4ogyK7OG_5v/view?usp=sharing
github_link: https://github.com/RahulVarmaC
linkedin: https://www.linkedin.com/in/rahulvarmac/
avatar: https://drive.google.com/file/d/1xoA6H5WKe4onku8JxMI_rdyL_l87mI9I/view?usp=sharing
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png 
